### ISSUE TITLE
Animation doesn't loop on React Native Web

### ISSUE THREAD

**Issue by sreuter** [tienph6m/react-native-animated-spinkit#7]
Animations don't seem to loop properly on React Native Web. They are only being played once.

**Comment by phamfoo** [comment]
Hi @sreuter,
This is happening because react-native-web doesn't have "native driver" support.
I added web support in `v1.5.0`, please give it a try. Keep in mind that without native driver support, all animations run on the JS thread. So you might want to use [SpinKit](https://github.com/tobiasahlin/SpinKit) instead for better performance.

**Comment by sreuter** [comment]
Aaaand.. it works, you're incredible :) Thanks @tienphaw !
